from flask_swagger_ui import get_swaggerui_blueprint
SWAGGER_URL = '/swagger'  # URL for exposing Swagger UI (can be customized)

# URL for accessing Swagger JSON (generated by flask-restx)
API_URL = 'swagger.json'

# Create a Swagger UI blueprint
swagger_ui_blueprint = get_swaggerui_blueprint(
    SWAGGER_URL,
    API_URL,
    config={
        'app_name': "Your Flask App"  # Customize the Swagger UI page title if needed
    }
)

# Register the blueprint in your Flask app
app.register_blueprint(swagger_ui_blueprint, url_prefix=SWAGGER_URL)
