version: 1
Template_name:
template_match_pattern: "cubb certificate of insurance"

Fields:
  abn:
   response_name: abn
   match_mechanism: json_path
   location: form.values[5].key
   parse: string_whitespace
   test: abn
