# statestore.yaml for Azure Blob storage component
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: coolfiles
spec:
  type: state.azure.blobstorage
  version: v1
  metadata:
    - name: accountName
      value: "formspocdocs2"
    - name: containerName
      value: docs
    - name: accountKey
      value: "aBf6Li/kWL6fYpdMt3Wx1AOnT9E8KA0DR7MnjvhVBG2t/GHI81uzcA/NMHRdXTzElgnK0tHS8e3e+AStE3M6qg=="
      #secretKeyRef: # Doesn't seem to be working... Dapr is trying to load state store component before the secret store, which will never work...
      #  name: blob-storage-secret-store
      #  key:  storage_key
auth:
  secretStore: blob-storage-secret-store
scopes:
  - formsapp
 