apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: form-recognizer-secret-store
spec:
  type: secretstores.local.file
  version: v1
  metadata:
  - name: secretsFile
    value: /etc/secrets/formrecognizer.secret.json # Note, per docker-compose.yml, this is your `secrets-for-running-locally/` directory
  - name: nestedSeparator
    value: ":"
