on: push

env:
  APP_RESOURCE_GROUP_NAME: "development-ocr"
  APP_RESOURCE_NAME: "devocrback"
  IMAGE_REGISTRY_HOSTNAME: "devocrregistry.azurecr.io"
  IMAGE_NAME: "coolforms"
  IMAGE_TAG: "latest"
  modelid: "neural_v1_6"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: test
        run: |
          cd app
          docker build --build-arg modelid=$modelid -t $IMAGE_NAME:$IMAGE_TAG .
          docker create --rm --name formsapp-testcontainer $IMAGE_NAME:$IMAGE_TAG python3 -m unittest discover -s tests -v
          docker start -a formsapp-testcontainer
  
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build
        run: |
          cd app
          docker build --build-arg modelid=$modelid -t $IMAGE_REGISTRY_HOSTNAME/$IMAGE_NAME:$IMAGE_TAG -t $IMAGE_REGISTRY_HOSTNAME/$IMAGE_NAME:$GITHUB_SHA .
          docker login -u ${{secrets.ARM_CLIENT_ID}} -p ${{secrets.ARM_CLIENT_SECRET}} $IMAGE_REGISTRY_HOSTNAME
          docker push $IMAGE_REGISTRY_HOSTNAME/$IMAGE_NAME:$IMAGE_TAG
          docker push $IMAGE_REGISTRY_HOSTNAME/$IMAGE_NAME:$GITHUB_SHA
  
  deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/azure-cli
    needs: build
    steps:
      - name: deploy
        run: |
          az extension add -n containerapp
          az login --service-principal --username ${{secrets.ARM_CLIENT_ID}} --password ${{secrets.ARM_CLIENT_SECRET}} --tenant ${{secrets.ARM_TENANT_ID}}
          az account set --subscription ${{secrets.ARM_SUBSCRIPTION_ID}}
          az containerapp update -n $APP_RESOURCE_NAME -g $APP_RESOURCE_GROUP_NAME -i $IMAGE_REGISTRY_HOSTNAME/$IMAGE_NAME:$GITHUB_SHA